# Generated by Django 5.0.4 on 2024-04-27 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя категории')),
                ('popularity', models.IntegerField(default=0, verbose_name='Популярность')),
                ('changeable', models.IntegerField(choices=[(0, 'нет'), (1, 'разрешено'), (2, 'только админ')], default=0, help_text='0 - нет, 1 - разрешено, 2 - только админ', verbose_name='Разрешено ли редактирование')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topic',
            },
        ),
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('thought', models.CharField(max_length=255, verbose_name='Вопрос или утверждение')),
                ('explanation', models.CharField(max_length=255, verbose_name='Раскрытие темы')),
                ('facts', models.JSONField(blank=True, null=True, verbose_name='Факты')),
                ('advice', models.JSONField(blank=True, null=True, verbose_name='Советы')),
                ('keywords', models.JSONField(blank=True, null=True, verbose_name='Ключевые слова')),
                ('changeable', models.IntegerField(choices=[(0, 'нет'), (1, 'разрешено'), (2, 'только админ')], default=0, help_text='0 - нет, 1 - разрешено, 2 - только админ', verbose_name='Разрешено ли редактирование')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='categ.topic', verbose_name='Категория, к которой принадлежат размышления')),
            ],
            options={
                'verbose_name': 'Reflection',
                'verbose_name_plural': 'Reflection',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение заведения')),
                ('name', models.CharField(max_length=255, verbose_name='Название заведения')),
                ('description', models.CharField(max_length=255, verbose_name='Описание заведения')),
                ('opening_hours', models.CharField(max_length=255, verbose_name='Режим работы')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('contacts', models.JSONField(verbose_name='Контакты заведения, соцсети и т. д.')),
                ('keywords', models.JSONField(blank=True, null=True, verbose_name='Ключевые слова')),
                ('changeable', models.IntegerField(choices=[(0, 'нет'), (1, 'разрешено'), (2, 'только админ')], default=0, help_text='0 - нет, 1 - разрешено, 2 - только админ', verbose_name='Разрешено ли редактирование')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='categ.topic', verbose_name='Категория, к которой принадлежат места')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Place',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=255, verbose_name='Фраза')),
                ('transcription', models.CharField(max_length=255, verbose_name='Транскрипция')),
                ('meaning', models.JSONField(verbose_name='Значения')),
                ('appropriateness', models.CharField(max_length=255, verbose_name='В каких ситуациях уместно использование этой фразы')),
                ('keywords', models.JSONField(blank=True, null=True, verbose_name='Ключевые слова')),
                ('changeable', models.IntegerField(choices=[(0, 'нет'), (1, 'разрешено'), (2, 'только админ')], default=0, help_text='0 - нет, 1 - разрешено, 2 - только админ', verbose_name='Разрешено ли редактирование')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='categ.topic', verbose_name='Категория, к которой принадлежат фразы')),
            ],
            options={
                'verbose_name': 'Phrase',
                'verbose_name_plural': 'Phrase',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение слова')),
                ('word', models.CharField(max_length=255, verbose_name='Слово на кириллице')),
                ('transcription', models.CharField(max_length=255, verbose_name='Транскрипция')),
                ('lexical_meaning', models.JSONField(verbose_name='Лексическое значение')),
                ('context', models.JSONField(verbose_name='Чаще всего используемый контекст')),
                ('changeable', models.IntegerField(choices=[(0, 'нет'), (1, 'разрешено'), (2, 'только админ')], default=0, help_text='0 - нет, 1 - разрешено, 2 - только админ', verbose_name='Разрешено ли редактирование')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='categ.topic', verbose_name='Категория, к которой принадлежат слова')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Word',
            },
        ),
    ]
