# Generated by Django 5.0.4 on 2024-04-28 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsPhrases',
            fields=[
                ('phrases_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID фразы к которой принадлежит статистика')),
                ('counTransitions', models.IntegerField(verbose_name='Количество переходов')),
                ('popularity', models.FloatField(editable=False, verbose_name='Популярность')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsPlaces',
            fields=[
                ('places_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID места к которому принадлежит статистика')),
                ('counTransitions', models.IntegerField(verbose_name='Количество переходов')),
                ('popularity', models.FloatField(editable=False, verbose_name='Популярность')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsReflections',
            fields=[
                ('reflections_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID размышления к которому принадлежит статистика')),
                ('counTransitions', models.IntegerField(verbose_name='Количество переходов')),
                ('popularity', models.FloatField(editable=False, verbose_name='Популярность')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsTopics',
            fields=[
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='statistics', serialize=False, to='categ.topic', verbose_name='Категория, к которой принадлежит статистика')),
                ('counTransitions', models.IntegerField(verbose_name='Количество переходов')),
                ('popularity', models.FloatField(editable=False, verbose_name='Популярность')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsWords',
            fields=[
                ('word_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID слова к которой принадлежит статистика')),
                ('counTransitions', models.IntegerField(verbose_name='Количество переходов')),
                ('popularity', models.FloatField(editable=False, verbose_name='Популярность')),
            ],
        ),
    ]
