# Generated by Django 5.0.4 on 2024-04-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsphrases',
            name='phrases_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID фразы к которой принадлежит статистика'),
        ),
        migrations.AlterField(
            model_name='statisticsplaces',
            name='places_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID места к которому принадлежит статистика'),
        ),
        migrations.AlterField(
            model_name='statisticsreflections',
            name='reflections_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID размышления к которому принадлежит статистика'),
        ),
        migrations.AlterField(
            model_name='statisticswords',
            name='word_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID слова к которой принадлежит статистика'),
        ),
    ]
